# Window dimensions
WINDOW_WIDTH = 700
WINDOW_HEIGHT = 600

# Grid dimensions
GRID_ROWS = 14
GRID_COLS = 12

# Grid position offsets
GRID_OFFSET_X = 170
GRID_OFFSET_Y = 60

# Cell dimensions
CELL_SIZE = 30
RADIUS = CELL_SIZE * 0.4

# Preview row position
INITIAL_ROWS = 4
LINE_RISE_INTERVAL = 5000
PREVIEW_OFFSET_Y = GRID_OFFSET_Y + GRID_ROWS * CELL_SIZE
BUBBLE_SPAWN_INTERVAL = LINE_RISE_INTERVAL // GRID_COLS

# UI
BG_COLOR = (60, 85, 183)
HOVER_COLOR = (255, 255, 255, 100)  # RGBA (alpha)
CONTOUR_COLOR = (0, 0, 0)
BONUS_POINT_COLOR = (68, 194, 56)
TEXT_COLOR = (255, 255, 255)
TITLE_COLOR = (68, 194, 56)
BUTTON_COLOR = (0, 0, 0)
BUTTON_HOVER_COLOR = (68, 194, 56)
INACTIVE_BUTTON_COLOR = (100, 100, 100)

# Animation settings
POP_ANIMATION_DURATION = 400  # ms
FALL_ANIMATION_DURATION = 300  # ms
LEVEL_COMPLETED_BONUS_DELAY = 50  # ms between each cell bonus
BONUS_TEXT_DURATION = 300  # ms for POINTS_PER_EMPTY_CELL text
COMPLETE_LEVEL_TEXT_DURATION = 2000  # ms
START_LEVEL_TEXT_DURATION = 2000  # ms
FPS = 60  # Frame rate

# Scoring
POINTS_PER_BUBBLE = 10

BASE_POINTS_PER_EMPTY_CELL = 5
INCREASE_POINTS_PER_EMPTY_CELL_PER_LEVEL = 5

# Special Bubbles
BOMB_SPAWN_CHANCE = 0.01
ROW_BOMB_SPAWN_CHANCE = 0.02
COLUMN_BOMB_SPAWN_CHANCE = 0.03

# Level settings
MAX_LEVEL = 6

MAX_RISES_BASE = 15
MAX_RISES_INCREASE_PER_LEVEL = 5

LINE_RISE_BASE_INTERVAL = 5000
LINE_RISE_DECREASE_PER_LEVEL = 500
MIN_LINE_RISE_INTERVAL = 2000
